backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Cats'
          name: "cats"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
    - label: "Reseñas"
      name: "reseñas"
      file: "content/reseñas.md"
      fields: 
        - { label: "Titulo", name: "titulo", widget: "string" }
        - label: "Reseñas"
          name: "reseñas"
          widget: list
          fields: 
            - { label: "Descripción", name: "descripcion", widget: "text" }
            - { label: "Autor", name: "autor", widget: "string" }